spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    ## https://stackoverflow.com/questions/50322550/hibernate-dialect-for-mysql-8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database-create-script.sql
