version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
            - v1-dependencies-
      - run: mvn install
      - run: mvn test
      - run: "mvn cobertura:cobertura"
      - run: "bash <(curl -s https://codecov.io/bash)"
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-
