version: 2

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

    override:
      - run: mvn integration-test
      - run: mvn jacoco:report

    post:
      - run: mkdir -p $CIRCLE_ARTIFACTS/site/jacoco
      - run: mv target/site/jacoco/ $CIRCLE_ARTIFACTS/site/jacoco
